/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductCategory = IDL.Variant({
  'automotive' : IDL.Null,
  'tools' : IDL.Null,
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'toys' : IDL.Null,
  'furniture' : IDL.Null,
  'beauty' : IDL.Null,
  'books' : IDL.Null,
  'sports' : IDL.Null,
  'electronics' : IDL.Null,
  'homeAppliances' : IDL.Null,
});
export const ProductCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const ProductListingInput = IDL.Record({
  'imageFiles' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
  'condition' : ProductCondition,
});
export const Time = IDL.Int;
export const ProductListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'category' : ProductCategory,
  'price' : IDL.Nat,
  'condition' : ProductCondition,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const PurchaseDetails = IDL.Record({
  'productId' : IDL.Nat,
  'paymentId' : IDL.Text,
  'buyer' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProductListing' : IDL.Func([ProductListingInput], [IDL.Nat], []),
  'createTracking' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(ChatMessage))],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(ProductListing)], ['query']),
  'getTracking' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseProduct' : IDL.Func([PurchaseDetails], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateTracking' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductCategory = IDL.Variant({
    'automotive' : IDL.Null,
    'tools' : IDL.Null,
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'toys' : IDL.Null,
    'furniture' : IDL.Null,
    'beauty' : IDL.Null,
    'books' : IDL.Null,
    'sports' : IDL.Null,
    'electronics' : IDL.Null,
    'homeAppliances' : IDL.Null,
  });
  const ProductCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ProductListingInput = IDL.Record({
    'imageFiles' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
    'condition' : ProductCondition,
  });
  const Time = IDL.Int;
  const ProductListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'category' : ProductCategory,
    'price' : IDL.Nat,
    'condition' : ProductCondition,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const PurchaseDetails = IDL.Record({
    'productId' : IDL.Nat,
    'paymentId' : IDL.Text,
    'buyer' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProductListing' : IDL.Func([ProductListingInput], [IDL.Nat], []),
    'createTracking' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(ChatMessage))],
        ['query'],
      ),
    'getProductById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProductListing)],
        ['query'],
      ),
    'getTracking' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseProduct' : IDL.Func([PurchaseDetails], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateTracking' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };