/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export type ProductCategory = { 'automotive' : null } |
  { 'tools' : null } |
  { 'clothing' : null } |
  { 'other' : null } |
  { 'toys' : null } |
  { 'furniture' : null } |
  { 'beauty' : null } |
  { 'books' : null } |
  { 'sports' : null } |
  { 'electronics' : null } |
  { 'homeAppliances' : null };
export type ProductCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export interface ProductListing {
  'id' : bigint,
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : string,
  'seller' : Principal,
  'timestamp' : Time,
  'category' : ProductCategory,
  'price' : bigint,
  'condition' : ProductCondition,
}
export interface ProductListingInput {
  'imageFiles' : Array<ExternalBlob>,
  'title' : string,
  'description' : string,
  'category' : ProductCategory,
  'price' : bigint,
  'condition' : ProductCondition,
}
export interface PurchaseDetails {
  'productId' : bigint,
  'paymentId' : string,
  'buyer' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProductListing' : ActorMethod<[ProductListingInput], bigint>,
  'createTracking' : ActorMethod<[Principal, bigint], bigint>,
  'getAllProducts' : ActorMethod<[], Array<ProductListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[bigint], [] | [Array<ChatMessage>]>,
  'getProductById' : ActorMethod<[bigint], [] | [ProductListing]>,
  'getTracking' : ActorMethod<[bigint], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'purchaseProduct' : ActorMethod<[PurchaseDetails], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateTracking' : ActorMethod<[bigint, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];